name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  #build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          cd fsd2-group24
          cd frontend
          npm install
          npm start
      

  
